### ISSUE TITLE
可以添加计算ks的模块吗?

### ISSUE THREAD

**Issue by firecatzkj** [data-science-tools/ScoreCardModel#1]
计算模型的ks

**Comment by hsz1273327** [comment]
额....老版本倒是有...不过这个版本训练的时候就可以打印对错的准确率和召回率这些个指标,其实还行了,下个小迭代#4 我会给评分卡模型加上....你要是闲着也可以贡献下代码,3q

**Comment by firecatzkj** [comment]
好的,我这边正好实现了一个ks的函数

**Comment by hsz1273327** [comment]
我这边写好了~~你弄下来试试~~
