### ISSUE TITLE
新增评分卡模型的子类ScoreCardWithKSModel

### ISSUE THREAD

**Issue by hsz1273327** [data-science-tools/ScoreCardModel#4]
新增评分卡模型的子类,有如下特性:

+ 可以用于绘制ks曲线
+ 可以通过得分获取其在训练数据总体上的百分位数,并打印以此为阈值时的预测效果.
+ 可以通过得分获取其在某一个数据集上的百分位数.
+ 可以通过在训练数据总体上的百分位数获取其对应的得分.并答应以此为阈值时的预测效果.

**Comment by firecatzkj** [comment]
其实要是再有一个smbinning的功能就完美了,我看了R的实现,感觉自己实现不了

**Comment by hsz1273327** [comment]
能讲讲这是啥不....不介意的话可以在项目wiki里科普下......没学过这个......另外R我也还给老师了...我把这个需求加到下下个迭代了 #5 这个工单我就关了哈~
